SHA added
Patch disabled due to an issue:
-- Applying patch fix_openni2.patch
-- Applying patch fix_config_osx.patch
CMake Error at scripts/cmake/z_vcpkg_apply_patches.cmake:34 (message):
  Applying patch failed: Checking patch CMake/unix_config.cmake...

  error: while searching for:

      ?
      if(APPLE)?
          set(FORCE_RSUSB_BACKEND ON)?
          set(BUILD_WITH_TM2 ON)?
      endif()?
      ?
      if(FORCE_RSUSB_BACKEND)?

  error: patch failed: CMake/unix_config.cmake:35

  error: CMake/unix_config.cmake: patch does not apply

Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive.cmake:153 (z_vcpkg_apply_patches)
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:8 (vcpkg_extract_source_archive)
  scripts/cmake/vcpkg_from_github.cmake:113 (vcpkg_extract_source_archive_ex)
  ports/realsense2/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:147 (include)