[qtwayland] Not supported on macos:
```
Installing 1581/2016 qtwayland:x64-osx...
Building qtwayland:x64-osx...
CMake Warning at ports/qtwayland/portfile.cmake:4 (message):
  qtwayland requires libwayland-dev from your system package manager.  You
  can install it with

  sudo apt install libwayland-dev

  on Ubuntu systems.
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)

-- Downloading https://download.qt.io/archive/qt/6.5/6.5.2/submodules/qtwayland-everywhere-src-6.5.2.tar.xz -> qtwayland-everywhere-src-6.5.2.tar.xz...
-- Extracting source /Users/vagrant/Data/downloads/qtwayland-everywhere-src-6.5.2.tar.xz
-- Using source at /Users/vagrant/Data/buildtrees/qtwayland/src/here-src-6-199f26667d.clean
-- Found external ninja('1.11.1').
-- Configuring x64-osx
-- Building x64-osx-dbg
-- Building x64-osx-rel
-- Performing post-build validation
warning: The folder /include is empty or not present. This indicates the library was not correctly installed.
warning: There should be no empty directories in /Users/vagrant/Data/packages/qtwayland_x64-osx. The following empty directories were found:

    /Users/vagrant/Data/packages/qtwayland_x64-osx/debug

warning: If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:
    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug")

error: Found 2 post-build check problem(s). To submit these ports to curated catalogs, please first correct the portfile: /Users/vagrant/Data/work/2/s/ports/qtwayland/portfile.cmake
error: building qtwayland:x64-osx failed with: POST_BUILD_CHECKS_FAILED
Elapsed time to handle qtwayland:x64-osx: 13 s
```