[vcpkg baseline][libsoup] disable search krb5 to fix ci pinpline error (#38750)
Fixes regression:
https://dev.azure.com/vcpkg/public/_build/results?buildId=102737&view=results
````
REGRESSION: libsoup:x64-linux failed with BUILD_FAILED
````
Error:
````
/mnt/vcpkg-ci/b/krb5/x64-linux-dbg/util/et/../.././../src/krb5-1-8a38cd677f.clean/src/include/k5-thread.h:381: undefined reference to `k5_os_mutex_unlock'
````
Installation order issue. libsoup automatically detect the presence of
krb5 and use it. Then the binary artifacts depend on krb5 binaries
without declaring them. So disable auto-detection of krb5 in libsoup.

- [x] Changes comply with the [maintainer
guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ ] ~~SHA512s are updated for each updated download.~~
- [ ] ~~The "supports" clause reflects platforms that may be fixed by
this new version.~~
- [ ] ~~Any fixed [CI
baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)
entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the
port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version
--all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

---------

Co-authored-by: Jon <v-zhli17@microsoft.com>