[vcpkg baseline][pocketpy] Don't install include/pybind11/* (#39571)
Detected by
https://dev.azure.com/vcpkg/public/_build/results?buildId=104413&view=results

```
error: The following files are already installed in /mnt/vcpkg-ci/installed/x64-linux and are in conflict with pocketpy:x64-linux
Installed by pybind11:x64-linux  
include/pybind11/embed.h
    include/pybind11/functional.h
    include/pybind11/operators.h
    include/pybind11/pybind11.h
    include/pybind11/stl.h
```

Broken by https://github.com/microsoft/vcpkg/pull/39510, in which
pybind11 support was added.