[easyhook] Also disable /ZI
In https://github.com/microsoft/vcpkg/pull/20757 I patch easyhook to remove /Zi in release builds, but in our most recent nightly build we got another failure https://dev.azure.com/vcpkg/public/_build/results?buildId=61519&view=artifacts&pathAsName=false&type=publishedArtifacts

```
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\cderr.h : fatal error C1073: Internal error involving incremental compilation(compiler file 'd:\a01\_work\6\s\src\vctools\Compiler\CxxFE\sl\p1\c\p0io.c', line 1257) [D:\buildtrees\easyhook\x86-windows-dbg\2.7.7097.0-e2e62d41f5.clean\EasyHookDll\EasyHookDll.vcxproj]
         C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\ddeml.h(37,1): fatal error C1001: Internal compiler error. [D:\buildtrees\easyhook\x86-windows-dbg\2.7.7097.0-e2e62d41f5.clean\EasyHookDll\EasyHookDll.vcxproj]
         D:\buildtrees\easyhook\x86-windows-dbg\2.7.7097.0-e2e62d41f5.clean\DriverShared\LocalHook\install.c(618,1): error C2471: cannot update program database '???' [D:\buildtrees\easyhook\x86-windows-dbg\2.7.7097.0-e2e62d41f5.clean\EasyHookDll\EasyHookDll.vcxproj]
```

This change also removes /ZI (which was used in debug builds) and /Gm (which is irrelevant since we aren't doing development work on Easyhook)