Deindex cub.
cub has been 'in the CUDA box' since at least CUDA 11, and this copy conflicts with the copy bundled with CUDA 12.8 we use in the build lab:

```
/usr/local/cuda/targets/x86_64-linux/include/thrust/system/cuda/config.h:122:2: error: #error The version of CUB in your include path is not compatible with this release of Thrust. CUB is now included in the CUDA Toolkit, so you no longer need to use your own checkout of CUB. Define THRUST_IGNORE_CUB_VERSION_CHECK to ignore this.
  122 | #error The version of CUB in your include path is not compatible with this release of Thrust. CUB is now included in the CUDA Toolkit, so you no longer need to use your own checkout of CUB. Define THRUST_IGNORE_CUB_VERSION_CHECK to ignore this.
      |  ^~~~~
```

Alternative to https://github.com/microsoft/vcpkg/pull/44220