[qt5-webengine] fix jumbo build error due to ResolveColor() redefinition
Both of the following two files define a static function
ResolveColor() with the exact same signature causing a redefinition
error when running a jumbo build

* third_party/blink/renderer/core/layout/svg/svg_layout_tree_as_text.cc
* third_party/blink/renderer/core/layout/svg/layout_svg_resource_paint_server.cc

Error reported:

    In file included from gen/third_party/blink/renderer/core/layout/svg/svg_layout_jumbo_4.cc:16:
    ./../../../../src/5.15.13-38459bd7fb.clean/src/3rdparty/chromium/third_party/blink/renderer/core/layout/svg/svg_layout_tree_as_text.cc:255:30: error: redefinition of 'base::Optional<blink::Color> blink::ResolveColor(const blink::ComputedStyle&, const blink::SVGPaint&, const blink::SVGPaint&)'
      255 | static base::Optional<Color> ResolveColor(const ComputedStyle& style,
          |                              ^~~~~~~~~~~~
    In file included from gen/third_party/blink/renderer/core/layout/svg/svg_layout_jumbo_4.cc:5:
    ./../../../../src/5.15.13-38459bd7fb.clean/src/3rdparty/chromium/third_party/blink/renderer/core/layout/svg/layout_svg_resource_paint_server.cc:97:30: note: 'base::Optional<blink::Color> blink::ResolveColor(const blink::ComputedStyle&, const blink::SVGPaint&, const blink::SVGPaint&)' previously defined here
       97 | static base::Optional<Color> ResolveColor(const ComputedStyle& style,
         |                              ^~~~~~~~~~~~
    In file included from gen/third_party/blink/renderer/core/layout/svg/svg_layout_jumbo_4.cc:16:
    ./../../../../src/5.15.13-38459bd7fb.clean/src/3rdparty/chromium/third_party/blink/renderer/core/layout/svg/svg_layout_tree_as_text.cc:255:30: warning: 'base::Optional<blink::Color> blink::ResolveColor(const blink::ComputedStyle&, const blink::SVGPaint&, const blink::SVGPaint&)' defined but not used [-Wunused-function]
      255 | static base::Optional<Color> ResolveColor(const ComputedStyle& style,

Fixes #37448

See also QTBUG-123328