Use absolute path for pkgconfig
When cross-compiling, VCPKG uses a copy of pkgconfig which has been
built for the current host.  It constructs a relative path, such as
`/Users/user/vcpkg/installed/x64-osx/../arm64-osx/tools/pkgconf/pkgconf`

If this is the first port being built, it is possible that the installed
directory for the target triplet does not exist yet.  In the example
given above, where we are cross-compiling to x64-osx from arm64-osx,
although the directory `/Users/user/vcpkg/installed/arm64-osx` does
exist, the directory `x64-osx` does not exist yet.  This causes the OS
to fail to properly compute the full path, result in an error message:

```
Call Stack (most recent call first):
  ports/ffmpeg/portfile.cmake:797 (x_vcpkg_pkgconfig_get_modules)
  scripts/ports.cmake:147 (include)
CMake Error at installed/arm64-osx/share/vcpkg-pkgconfig-get-modules/x_vcpkg_pkgconfig_get_modules.cmake:28 (execute_process):
  execute_process error getting child return code: No such file or directory
Call Stack (most recent call first):
  ports/ffmpeg/portfile.cmake:797 (x_vcpkg_pkgconfig_get_modules)
  scripts/ports.cmake:147 (include)
error: building ffmpeg:x64-osx-dynamic failed with: BUILD_FAILED
```

This PR fixes that problem by calling `get_filename_component([..] ABSOLUTE)`
to compute the absolute path to pkgconfig.

This also applies when the target triplet is a variation of the source
triplet, e.g. compiling for `x64-linux-dynamic` (in which case the
host triplet is still `x64-linux`).

Fixes #32887