[vcpkg] Fix unrecognized identifer errors in prbuild and cibuild.
Error: Unrecognized identifer name false. Add to override list in triplet file.
tensorflow-common's version numbers are unchanged because there is no effect on any consumers.

Error: Unrecognized identifer name ios. Add to override list in triplet file.
This is used in the "ashes" port and is recognized by the community triplet x64-ios.