[pcre2] Fix "There should be no absolute paths" (#37971)
Problem occurs also on x64-linux-dynamic.

```
warning: There should be no absolute paths, such as the following, in an installed package:
  /home/XXX/prog/vcpkg/packages/pcre2_x64-linux-dynamic
  /home/XXX/prog/vcpkg/installed
  /home/XXX/prog/vcpkg/buildtrees/pcre2
  /home/XXX/prog/vcpkg/downloads
Absolute paths were found in the following files:
  /home/XXX/prog/vcpkg/packages/pcre2_x64-linux-dynamic/bin/pcre2-config
  /home/XXX/prog/vcpkg/packages/pcre2_x64-linux-dynamic/debug/bin/pcre2-config
error: Found 1 post-build check problem(s). To submit these ports to curated catalogs, please first correct the portfile: /home/XXX/prog/vcpkg/ports/pcre2/portfile.cmake
```

- [ ] Changes comply with the [maintainer
guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [X] SHA512s are updated for each updated download.
- ~~[ ] The "supports" clause reflects platforms that may be fixed by
this new version.~~
- ~~[ ] Any fixed [CI
baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)
entries are removed from that file.~~
- ~~[ ] Any patches that are no longer applied are deleted from the
port's directory.~~
- [X] The version database is fixed by rerunning `./vcpkg x-add-version
--all` and committing the result.
- [X] Only one version is added to each modified port's versions file.