Fix namespace clashing between cub and thrust::cub.
Fix VS2022 error C3052: 'k': variable doesn't appear in a data-sharing clause under a default(none) clause