[ftxui] Drop UWP support
According to the build log:
D:\buildtrees\ftxui\src\719840ffdc-7f05139eb7.clean\src\ftxui\screen\terminal.cpp(56,37): error C2039: 'getenv': is not a member of 'std' [D:\buildtrees\ftxui\x64-uwp-dbg\screen.vcxproj]
D:\buildtrees\ftxui\src\719840ffdc-7f05139eb7.clean\src\ftxui\screen\terminal.cpp(60,32): error C2039: 'getenv': is not a member of 'std' [D:\buildtrees\ftxui\x64-uwp-dbg\screen.vcxproj]
ftxui can not be built successfully on UWP, since `getenv` is unavailable on UWP.

https://docs.microsoft.com/en-us/cpp/cppcx/crt-functions-not-supported-in-universal-windows-platform-apps?view=msvc-160