[duckdb] Avoid stdext::checked_array_iterator.
I initially tried devendoring fmt but they have put it in its own namespace that makes it not devendorable.

Resolves:

```
\third_party\fmt\include\fmt/format.h(326): error C2653: 'stdext': is not a class or namespace name
\third_party\fmt\include\fmt/format.h(326): error C2061: syntax error: identifier 'checked_array_iterator'
\third_party\fmt\include\fmt/format.h(327): error C2988: unrecognizable template declaration/definition
\third_party\fmt\include\fmt/format.h(327): error C2143: syntax error: missing ';' before '<'
\third_party\fmt\include\fmt/format.h(327): error C2059: syntax error: '<'
\third_party\fmt\include\fmt/format.h(327): error C2143: syntax error: missing ';' before '{'
\third_party\fmt\include\fmt/format.h(327): error C2447: '{': missing function header (old-style formal list?)
\third_party\fmt\include\fmt/format.h(335): warning C4346: 'value': dependent name is not a type
\third_party\fmt\include\fmt/format.h(335): note: prefix the qualified-id with 'typename' to indicate a type
\third_party\fmt\include\fmt/format.h(336): error C2988: unrecognizable template declaration/definition
\third_party\fmt\include\fmt/format.h(336): error C2143: syntax error: missing ';' before '<'
\third_party\fmt\include\fmt/format.h(336): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
\third_party\fmt\include\fmt/format.h(336): error C2059: syntax error: '<'
\third_party\fmt\include\fmt/format.h(336): error C2653: 'Container': is not a class or namespace name
\third_party\fmt\include\fmt/format.h(337): error C2065: 'Container': undeclared identifier
\third_party\fmt\include\fmt/format.h(337): error C2923: 'std::back_insert_iterator': 'Container' is not a valid template type argument for parameter '_Container'
\third_party\fmt\include\fmt/format.h(337): note: see declaration of 'Container'
\third_party\fmt\include\fmt/format.h(337): error C2143: syntax error: missing ';' before '{'
\third_party\fmt\include\fmt/format.h(337): error C2447: '{': missing function header (old-style formal list?)
```