[games101-cgl] Deindex in favor of coin-or-cgl
I resolved this conflict in favor of the coin-or versions because they have been in our registry longer, and have upstream activity.

Resolves

```
error: The following files are already installed in D:/installed/x86-windows and are in conflict with games101-cgl:x86-windows
Installed by coin-or-cgl:x86-windows: lib/Cgl.lib
```