Build fixes from 2020-01-18 build
https://dev.azure.com/vcpkg/public/_build/results?buildId=48065

> PASSING, REMOVE FROM FAIL LIST: chartdir:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: cmark:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: cppcms:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: cudnn:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: devicenameresolver:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: dxut:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: epsilon:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: fann:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: getopt-win32:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: glib:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: graphqlparser:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: halide:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: hpx:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: jemalloc:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: libepoxy:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: libhsplasma:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: libmodman:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: libpcap:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: libplist:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: milerius-sfml-imgui:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: monkeys-audio:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: moos-core:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: msix:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: ngspice:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: openni2:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: openvr:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: pmdk:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: pngpp:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: qpid-proton:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: qt5-tools:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: sciter:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: scylla-wrapper:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: soundtouch:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: spirv-tools:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: torch-th:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: treehopper:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: unrar:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: urdfdom:x64-windows-static-md (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: xalan-c:x64-windows-static-md (.\scripts\ci.baseline.txt)

These look like they have always passed since we turned on x64-windows-static-md in nightly CI.

>PASSING, REMOVE FROM FAIL LIST: osgearth:x64-windows (.\scripts\ci.baseline.txt)
>PASSING, REMOVE FROM FAIL LIST: osgearth:x86-windows (.\scripts\ci.baseline.txt)

Maybe addressed by https://github.com/microsoft/vcpkg/pull/15777

>REGRESSION: gettext:arm-uwp. If expected, add gettext:arm-uwp=fail to .\scripts\ci.baseline.txt.
>REGRESSION: gettext:arm64-windows. If expected, add gettext:arm64-windows=fail to .\scripts\ci.baseline.txt.

Probably fixed by https://github.com/microsoft/vcpkg/pull/15740

> PASSING, REMOVE FROM FAIL LIST: directxmesh:x64-linux (.\scripts\ci.baseline.txt)
> PASSING, REMOVE FROM FAIL LIST: uvatlas:x64-linux (.\scripts\ci.baseline.txt)

Probably an error in the authoring of https://github.com/microsoft/vcpkg/pull/15554/

> REGRESSION: dcmtk:x86-windows. If expected, add dcmtk:x86-windows=fail to .\scripts\ci.baseline.txt.
>
> "C:\PROGRA~2\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x86\cl.exe"   /TP -DDCMTK_BUILD_IN_PROGRESS -DNOMINMAX -DUSE_NULL_SAFE_OFSTRING -D_CRT_FAR_MAPPINGS_NO_DEPRECATE -D_CRT_IS_WCTYPE_NO_DEPRECATE -D_CRT_MANAGED_FP_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE_GLOBALS -D_CRT_SETERRORMODE_BEEP_SLEEP_NO_DEPRECATE -D_CRT_TIME_FUNCTIONS_NO_DEPRECATE -D_CRT_VCCLRIT_NO_DEPRECATE -D_REENTRANT -D_SCL_SECURE_NO_DEPRECATE -Dofstd_EXPORTS -ID:\installed\x86-windows\include -Iconfig\include -ID:\buildtrees\dcmtk\src\95da808b49-b82aa35f79.clean\ofstd\include -ID:\buildtrees\dcmtk\src\95da808b49-b82aa35f79.clean\oflog\include -ID:\buildtrees\dcmtk\src\95da808b49-b82aa35f79.clean\dcmdata\include -ID:\buildtrees\dcmtk\src\95da808b49-b82aa35f79.clean\dcmimgle\include -ID:\buildtrees\dcmtk\src\95da808b49-b82aa35f79.clean\dcmimage\include -ID:\buildtrees\dcmtk\src\95da808b49-b82aa35f79.clean\dcmjpeg\include -ID:\buildtrees\dcmtk\src\95da808b49-b82aa35f79.clean\dcmjpls\include -ID:\buildtrees\dcmtk\src\95da808b49-b82aa35f79.clean\dcmtls\include -ID:\buildtrees\dcmtk\src\95da808b49-b82aa35f79.clean\dcmnet\include -ID:\buildtrees\dcmtk\src\95da808b49-b82aa35f79.clean\dcmsr\include -ID:\buildtrees\dcmtk\src\95da808b49-b82aa35f79.clean\dcmsign\include -ID:\buildtrees\dcmtk\src\95da808b49-b82aa35f79.clean\dcmwlm\include -ID:\buildtrees\dcmtk\src\95da808b49-b82aa35f79.clean\dcmqrdb\include -ID:\buildtrees\dcmtk\src\95da808b49-b82aa35f79.clean\dcmpstat\include -ID:\buildtrees\dcmtk\src\95da808b49-b82aa35f79.clean\dcmrt\include -ID:\buildtrees\dcmtk\src\95da808b49-b82aa35f79.clean\dcmiod\include -ID:\buildtrees\dcmtk\src\95da808b49-b82aa35f79.clean\dcmfg\include -ID:\buildtrees\dcmtk\src\95da808b49-b82aa35f79.clean\dcmseg\include -ID:\buildtrees\dcmtk\src\95da808b49-b82aa35f79.clean\dcmtract\include -ID:\buildtrees\dcmtk\src\95da808b49-b82aa35f79.clean\dcmpmap\include -ID:\buildtrees\dcmtk\src\95da808b49-b82aa35f79.clean\dcmect\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -DDEBUG /showIncludes /Foofstd\libsrc\CMakeFiles\ofstd.dir\offilsys.cc.obj /Fdofstd\libsrc\CMakeFiles\ofstd.dir\ofstd.pdb /FS -c D:\buildtrees\dcmtk\src\95da808b49-b82aa35f79.clean\ofstd\libsrc\offilsys.cc
> D:\buildtrees\dcmtk\src\95da808b49-b82aa35f79.clean\ofstd\libsrc\offilsys.cc(376): error C2039: 'DIR': is not a member of '`global namespace''
>
> REGRESSION: tesseract:x64-windows-static-md. If expected, add tesseract:x64-windows-static-md=fail to .\scripts\ci.baseline.txt.
> REGRESSION: tesseract:x64-windows-static. If expected, add tesseract:x64-windows-static=fail to .\scripts\ci.baseline.txt.
> REGRESSION: tesseract:x64-windows. If expected, add tesseract:x64-windows=fail to .\scripts\ci.baseline.txt.
> REGRESSION: tesseract:x86-windows. If expected, add tesseract:x86-windows=fail to .\scripts\ci.baseline.txt.
> [2/241] "C:\PROGRA~2\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x86\cl.exe"   /TP -DHAVE_CONFIG_H -DTESS_EXPORTS -D_CRT_SECURE_NO_WARNINGS -D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS=1 -D__AVX2__ -D__AVX__ -D__BMI2__ -D__FMA__ -D__SSE2__ -D__SSE3__ -D__SSE4A__ -D__SSE4_1__ -D__SSE4_2__ -D__SSSE3__ -Dlibtesseract_EXPORTS -ID:\installed\x86-windows\share\leptonica\..\..\include -ID:\installed\x86-windows\share\leptonica\..\..\include\leptonica -I. -ID:\buildtrees\tesseract\src\4.1.1-3a7d5a1d2b.clean\src\api -Iapi -ID:\buildtrees\tesseract\src\4.1.1-3a7d5a1d2b.clean\src\arch -ID:\buildtrees\tesseract\src\4.1.1-3a7d5a1d2b.clean\src\ccmain -ID:\buildtrees\tesseract\src\4.1.1-3a7d5a1d2b.clean\src\ccstruct -ID:\buildtrees\tesseract\src\4.1.1-3a7d5a1d2b.clean\src\ccutil -ID:\buildtrees\tesseract\src\4.1.1-3a7d5a1d2b.clean\src\classify -ID:\buildtrees\tesseract\src\4.1.1-3a7d5a1d2b.clean\src\cutil -ID:\buildtrees\tesseract\src\4.1.1-3a7d5a1d2b.clean\src\dict -ID:\buildtrees\tesseract\src\4.1.1-3a7d5a1d2b.clean\src\lstm -ID:\buildtrees\tesseract\src\4.1.1-3a7d5a1d2b.clean\src\opencl -ID:\buildtrees\tesseract\src\4.1.1-3a7d5a1d2b.clean\src\textord -ID:\buildtrees\tesseract\src\4.1.1-3a7d5a1d2b.clean\src\viewer -ID:\buildtrees\tesseract\src\4.1.1-3a7d5a1d2b.clean\src\wordrec -ID:\buildtrees\tesseract\src\4.1.1-3a7d5a1d2b.clean\src\training -ID:\buildtrees\tesseract\src\4.1.1-3a7d5a1d2b.clean\src\vs2010\tesseract -ID:\installed\x86-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /utf-8 /MP /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /W4 /bigobj -std:c++17 /showIncludes /FoCMakeFiles\libtesseract.dir\src\classify\shapetable.cpp.obj /FdCMakeFiles\libtesseract.dir\ /FS -c D:\buildtrees\tesseract\src\4.1.1-3a7d5a1d2b.clean\src\classify\shapetable.cpp
> FAILED: CMakeFiles/libtesseract.dir/src/classify/shapetable.cpp.obj
> "C:\PROGRA~2\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x86\cl.exe"   /TP -DHAVE_CONFIG_H -DTESS_EXPORTS -D_CRT_SECURE_NO_WARNINGS -D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS=1 -D__AVX2__ -D__AVX__ -D__BMI2__ -D__FMA__ -D__SSE2__ -D__SSE3__ -D__SSE4A__ -D__SSE4_1__ -D__SSE4_2__ -D__SSSE3__ -Dlibtesseract_EXPORTS -ID:\installed\x86-windows\share\leptonica\..\..\include -ID:\installed\x86-windows\share\leptonica\..\..\include\leptonica -I. -ID:\buildtrees\tesseract\src\4.1.1-3a7d5a1d2b.clean\src\api -Iapi -ID:\buildtrees\tesseract\src\4.1.1-3a7d5a1d2b.clean\src\arch -ID:\buildtrees\tesseract\src\4.1.1-3a7d5a1d2b.clean\src\ccmain -ID:\buildtrees\tesseract\src\4.1.1-3a7d5a1d2b.clean\src\ccstruct -ID:\buildtrees\tesseract\src\4.1.1-3a7d5a1d2b.clean\src\ccutil -ID:\buildtrees\tesseract\src\4.1.1-3a7d5a1d2b.clean\src\classify -ID:\buildtrees\tesseract\src\4.1.1-3a7d5a1d2b.clean\src\cutil -ID:\buildtrees\tesseract\src\4.1.1-3a7d5a1d2b.clean\src\dict -ID:\buildtrees\tesseract\src\4.1.1-3a7d5a1d2b.clean\src\lstm -ID:\buildtrees\tesseract\src\4.1.1-3a7d5a1d2b.clean\src\opencl -ID:\buildtrees\tesseract\src\4.1.1-3a7d5a1d2b.clean\src\textord -ID:\buildtrees\tesseract\src\4.1.1-3a7d5a1d2b.clean\src\viewer -ID:\buildtrees\tesseract\src\4.1.1-3a7d5a1d2b.clean\src\wordrec -ID:\buildtrees\tesseract\src\4.1.1-3a7d5a1d2b.clean\src\training -ID:\buildtrees\tesseract\src\4.1.1-3a7d5a1d2b.clean\src\vs2010\tesseract -ID:\installed\x86-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /utf-8 /MP /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /W4 /bigobj -std:c++17 /showIncludes /FoCMakeFiles\libtesseract.dir\src\classify\shapetable.cpp.obj /FdCMakeFiles\libtesseract.dir\ /FS -c D:\buildtrees\tesseract\src\4.1.1-3a7d5a1d2b.clean\src\classify\shapetable.cpp
> cl : Command line warning D9025 : overriding '/W3' with '/W4'
> D:\installed\x86-windows\include\params.h(36): error C2143: syntax error: missing ';' before '*'

https://github.com/microsoft/vcpkg/pull/15785

> REGRESSION: fluidsynth:x64-windows-static-md. If expected, add fluidsynth:x64-windows-static-md=fail to .\scripts\ci.baseline.txt.

Was previously a cascaded failure from glib.

REGRESSION: libevent:x86-windows. If expected, add libevent:x86-windows=fail to .\scripts\ci.baseline.txt.

> REGRESSION: ideviceinstaller:x64-windows-static-md. If expected, add ideviceinstaller:x64-windows-static-md=fail to .\scripts\ci.baseline.txt.
> REGRESSION: libcrafter:x64-windows-static-md. If expected, add libcrafter:x64-windows-static-md=fail to .\scripts\ci.baseline.txt.
> REGRESSION: libirecovery:x64-windows-static-md. If expected, add libirecovery:x64-windows-static-md=fail to .\scripts\ci.baseline.txt.
> REGRESSION: moos-essential:x64-windows-static-md. If expected, add moos-essential:x64-windows-static-md=fail to .\scripts\ci.baseline.txt.
> REGRESSION: openmama:x64-windows-static-md. If expected, add openmama:x64-windows-static-md=fail to .\scripts\ci.baseline.txt.
> REGRESSION: sdformat10:x64-windows-static-md. If expected, add sdformat10:x64-windows-static-md=fail to .\scripts\ci.baseline.txt.
> REGRESSION: sdformat6:x64-windows-static-md. If expected, add sdformat6:x64-windows-static-md=fail to .\scripts\ci.baseline.txt.
> REGRESSION: sdformat9:x64-windows-static-md. If expected, add sdformat9:x64-windows-static-md=fail to .\scripts\ci.baseline.txt.

I'm going to assume these were cascaded failures for now.

> REGRESSION: mesa:x64-windows-static-md. If expected, add mesa:x64-windows-static-md=fail to .\scripts\ci.baseline.txt.
> REGRESSION: mesa:x64-windows. If expected, add mesa:x64-windows=fail to .\scripts\ci.baseline.txt.
> REGRESSION: mesa:x86-windows. If expected, add mesa:x86-windows=fail to .\scripts\ci.baseline.txt.

Nancy is working on this https://github.com/microsoft/vcpkg/pull/15729

> REGRESSION: quirc:x64-linux. If expected, add quirc:x64-linux=fail to .\scripts\ci.baseline.txt.
> REGRESSION: quirc:x64-osx. If expected, add quirc:x64-osx=fail to .\scripts\ci.baseline.txt.
> Starting package 1166/1442: quirc:x64-linux
> Building package quirc[core]:x64-linux...
> -- Downloading https://github.com/dlbeer/quirc/archive/7e7ab596e4d0988faf1c12ae89c354b114181c40.tar.gz -> dlbeer-quirc-7e7ab596e4d0988faf1c12ae89c354b114181c40.tar.gz...
> -- Extracting source /mnt/vcpkg-ci/downloads/dlbeer-quirc-7e7ab596e4d0988faf1c12ae89c354b114181c40.tar.gz
> -- Using source at /mnt/vcpkg-ci/buildtrees/quirc/src/b114181c40-f1e71e0d5b.clean
> -- Configuring x64-linux-dbg
> -- Configuring x64-linux-rel
> -- Building x64-linux-dbg
> -- Building x64-linux-rel
> -- Installing: /mnt/vcpkg-ci/packages/quirc_x64-linux/share/quirc/copyright/LICENSE
> -- Performing post-build validation
> -- Performing post-build validation done
> Uploaded binaries to 1 HTTP remotes.
> Building package quirc[core]:x64-linux... done
> Installing package quirc[core]:x64-linux...
> The following files are already installed in /mnt/vcpkg-ci/installed/x64-linux and are in conflict with quirc:x64-linux
>
> Installed by opencv4:x64-linux
>     lib/libquirc.a
>
> Elapsed time for package quirc:x64-linux: 2.531 s

Probably broken by https://github.com/microsoft/vcpkg/pull/15089, fix here

> REGRESSION: spatialite-tools:x64-linux. If expected, add spatialite-tools:x64-linux=fail to .\scripts\ci.baseline.txt.
> REGRESSION: spatialite-tools:x64-osx. If expected, add spatialite-tools:x64-osx=fail to .\scripts\ci.baseline.txt.

These are spewing linker errors, probably triggered by https://github.com/microsoft/vcpkg/pull/15768/ although that PR removed them from ci.baseline.txt?