Fix many many bugs in the changelog generation script:
84: Pass StartDate and EndDate to Get-MergedPullRequests instead of special casing only Credentials
109+130: Fix calculating negative progress caused by seeing PRs in the future because GitHub returns times in UTC
268: Actually make filtering for infrastructure PRs functional
303: Fix extraction of port-version from vcpkg.json. This really should be handled by diffing baseline.json in the future.
374-382: Fix expression ordering and casting problem which prevented non-CONTROL ports from ever being considered "new"

Also skip emitting headers for empty blocks, update and sort current triplet list, and move infrastructure bits below
port modifications.

Example output:

vcpkg (2022.02.19 - 2022.02.22)
---
#### Total port count:
#### Total port count per triplet (tested):
|triplet|ports available|
|---|---|
|x86-windows|NUM|
|**x64-windows**|NUM|
|x64-windows-static|NUM|
|x64-windows-static-md|NUM|
|x64-uwp|NUM|
|arm64-windows|NUM|
|arm-uwp|NUM|
|**x64-osx**|NUM|
|**x64-linux**|NUM|
<details>
<summary><b>The following 2 ports have been added:</b></summary>

|port|version|
|---|---|
|[libcurl-simple-https](https://github.com/microsoft/vcpkg/pull/22917)|2022-02-14
|[triton](https://github.com/microsoft/vcpkg/pull/23111)|0.9

</details>
<details>
<summary><b>The following 18 ports have been updated:</b></summary>

- polyhook2 `2022-02-06#0` -> `2022-02-21#0`
    - [(#23203)](https://github.com/microsoft/vcpkg/pull/23203) [polyhook2] Update to latest (2022-02-21) (by @acidicoala)
- graphviz `2.49.1#1` -> `2.49.1#2`
    - [(#23148)](https://github.com/microsoft/vcpkg/pull/23148) [graphviz] Fix tools (by @Ace314159)
- itk `5.1.0#7` -> `5.2.1#0`
    - [(#23158)](https://github.com/microsoft/vcpkg/pull/23158) [ITK] update to v5.2.1 (by @Adela0814)
- qhull `8.0.2#2` -> `8.0.2#3`
    - [(#23129)](https://github.com/microsoft/vcpkg/pull/23129) [qhull] Fix copyright, pc files, cmake usage (by @dg0yt)
- tgui `2021-04-19#2` -> `2021-04-19#3`
    - [(#23211)](https://github.com/microsoft/vcpkg/pull/23211) [tgui] fix absolute paths (by @autoantwort)
- json-dto `0.3.0#0` -> `0.3.1#0`
    - [(#23224)](https://github.com/microsoft/vcpkg/pull/23224) [json-dto] Update to 0.3.1 (by @eao197)
- leveldb `1.22#4` -> `1.22#5`
    - [(#23180)](https://github.com/microsoft/vcpkg/pull/23180) [leveldb] Fix homepage (by @MarcoFalke)
- openxr-loader `1.0.22#0` -> `1.0.22#1`
    - [(#23191)](https://github.com/microsoft/vcpkg/pull/23191) [openxr-loader] Fix build failure in world rebuild CI. (by @Hoikas)
- ngspice `35#1` -> `35#2`
    - [(#23151)](https://github.com/microsoft/vcpkg/pull/23151) [ngspice] Fix error C2065 (by @Cheney-W)
- openmvg `2.0#1` -> `2.0#2`
    - [(#23114)](https://github.com/microsoft/vcpkg/pull/23114) [cereal] Update to 1.3.1 (by @mapret)
- lazy-importer `2021-10-23#0` -> `2022-02-09#0`
    - [(#23192)](https://github.com/microsoft/vcpkg/pull/23192) [lazy-importer] Update to 2022-02-09 (by @Thomas1664)
- gstreamer `1.19.2#3` -> `1.19.2#4`
    - [(#23125)](https://github.com/microsoft/vcpkg/pull/23125) [gstreamer] Support arm-windows and add features (by @JackBoosY)
- charls `2.2.0#2` -> `2.3.4#0`
    - [(#23189)](https://github.com/microsoft/vcpkg/pull/23189) [charls] Update to 2.3.4 (by @Thomas1664)
- arrow `7.0.0#0` -> `7.0.0#1`
    - [(#23188)](https://github.com/microsoft/vcpkg/pull/23188) [arrow] add plasma support for non Windows platforms (by @fran6co)
- trantor `1.5.4#0` -> `1.5.5#0`
    - [(#23182)](https://github.com/microsoft/vcpkg/pull/23182) [trantor] Update to 1.5.5 (by @an-tao)
- capstone `4.0.2#2` -> `4.0.2#3`
    - [(#23122)](https://github.com/microsoft/vcpkg/pull/23122) [capstone] Use static runtime if capstone wants to be statically linked (by @illera88)
- gainput `1.0.0#4` -> `1.0.0#5`
    - [(#23219)](https://github.com/microsoft/vcpkg/pull/23219) [gainput] Support Linux (by @JackBoosY)
- cereal `1.3.0#1` -> `1.3.1#0`
    - [(#23114)](https://github.com/microsoft/vcpkg/pull/23114) [cereal] Update to 1.3.1 (by @mapret)

</details>
<details>
<summary>The following additional changes have been made to vcpkg's infrastructure:</summary>

- [(#23045)](https://github.com/microsoft/vcpkg/pull/23045) [vcpkg docs] Update ko_KR translation (by @jnooree)
- [(#23181)](https://github.com/microsoft/vcpkg/pull/23181) [vcpkg doc] Fixes typo in vcpkg_download_distfile.cmake (by @acd1034)

</details>
-- vcpkg team vcpkg@microsoft.com Thu, 24 February 00:29:57 -0800