ci.baseline.txt: Skip ports that hate __n64 __uint64x1_t_to_n64(uint64x1_t)
This is due to a problem with <wchar.h>. Sorry @cenit !

C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1443~1.348\bin\Hostx64\arm64\cl.exe   /TP  -external:ID:\installed\arm64-windows\include -external:W0 /nologo /DWIN32 /D_WINDOWS /utf-8 /GR /EHsc /MP  /MDd /Z7 /Ob0 /Od /RTC1  -MDd -MP -GR- -GF -Zc:__cplusplus -Zc:inline -Zc:strictStrings -Zc:threadSafeInit- -W4 -Zc:arm64-aliased-neon-types- -GS /showIncludes /FoCMakeFiles\blend2d.dir\src\blend2d\matrix_avx.cpp.obj /FdCMakeFiles\blend2d.dir\ /FS -c D:\b\blend2d\src\35679d7f82-3427ecd9ab.clean\src\blend2d\matrix_avx.cpp
cl : Command line warning D9025 : overriding '/GR' with '/GR-'
C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\wchar.h(254): error C2664: '__n64 __uint64x1_t_to_n64(uint64x1_t)': cannot convert argument 1 from 'uint16x4_t' to 'uint64x1_t'
C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\wchar.h(254): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.43.34808\include\arm64_neon.h(1957): note: see declaration of '__uint64x1_t_to_n64'
C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\wchar.h(254): note: while trying to match the argument list '(uint16x4_t)'
C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\wchar.h(381): error C2664: '__n64 __uint64x1_t_to_n64(uint64x1_t)': cannot convert argument 1 from 'uint16x4_t' to 'uint64x1_t'
C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\wchar.h(381): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.43.34808\include\arm64_neon.h(1957): note: see declaration of '__uint64x1_t_to_n64'
C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\wchar.h(381): note: while trying to match the argument list '(uint16x4_t)'