[folly related] update to 05.20 (#38931)
Update `folly` and its related ports to the latest version
`2024.05.20.00`.

The recent update to `folly` includes this commit:
https://github.com/facebook/folly/commit/99767aa88e8fd77823c870491d639723cf570b9d,
which caused downstream `rsocket` to fail with the following error
during build.
```
vcpkg\rsocket\src\84ec7fc921-d730564084\rsocket\RSocketServer.cpp(32): error C2665: 'folly::ThreadLocal<rsocket::SetupResumeAcceptor,rsocket::RSocketServer::SetupResumeAcceptorTag,void>::ThreadLocal': no overloaded function could convert all the argument types
```
A patch has now been submitted to fix this issue.
- [x] Changes comply with the [maintainer
guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [ ] ~The "supports" clause reflects platforms that may be fixed by
this new version.~
- [ ] ~Any fixed [CI
baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)
entries are removed from that file.~
- [ ] ~Any patches that are no longer applied are deleted from the
port's directory.~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version
--all` and committing the result.
- [x] Only one version is added to each modified port's versions file.