[qtbase] fix windows with dnslookup feature
Setting FEATURE_libresolv unconditionally breaks windows:

```
ERROR: Feature "libresolv": Forcing to "ON" breaks its condition:
    WrapResolv_FOUND
Condition values dump:
    WrapResolv_FOUND = "FALSE"
```