[influxdb-cxx] Avoid conflict with libproxy.
Use upstream's setting INFLUXCXX_INSTALL_HEADER_TO_SUBDIR

Resolves:

```
error: The following files are already installed in D:/installed/x86-windows and are in conflict with libproxy:x86-windows
Installed by influxdb-cxx:x86-windows: include/Proxy.h
```