REGRESSION: chartdir:x64-linux. If expected, add chartdir:x64-linux=fail to .\scripts\ci.baseline.txt.
-- Note: chartdir only supports dynamic library linkage. Building dynamic library.
-- Downloading http://www.advsofteng.net/chartdir_cpp_linux_64.tar.gz -> chartdir_cpp_linux_64-7.0.0.tar.gz...
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] popen(curl --fail -L "https://vcpkgassetcache.blob.core.windows.net/assets/e7e71b64b3a756b6df174758c392ab4c9310b4d265e521dccbd009eeefd46e021a74572e7212de5564725df20ddf189e1599e88a116b426f1256f7d34b0131aa?sp=racwl&st=2021-06-29T20:09:46Z&se=2021-10-02T04:09:46Z&spr=https&sv=2020-08-04&sr=c&sig=g3shlIpD0R923OUzfIsrTwjX0vc6OzNXGEDO3URXmYc%3D" --create-dirs --output /mnt/vcpkg-ci/downloads/chartdir_cpp_linux_64-7.0.0.tar.gz.1003174.part 2>&1)
[DEBUG] cmd_execute_and_stream_data() returned 5632 after    31162 us
[DEBUG] popen(curl --fail -L http://www.advsofteng.net/chartdir_cpp_linux_64.tar.gz --create-dirs --output /mnt/vcpkg-ci/downloads/chartdir_cpp_linux_64-7.0.0.tar.gz.1003174.part 2>&1)
[DEBUG] cmd_execute_and_stream_data() returned 0 after  8512565 us
Error: Failed to download from mirror set:
https://vcpkgassetcache.blob.core.windows.net/assets/e7e71b64b3a756b6df174758c392ab4c9310b4d265e521dccbd009eeefd46e021a74572e7212de5564725df20ddf189e1599e88a116b426f1256f7d34b0131aa?*** SECRET ***:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

File does not have the expected hash:
             url : [ http://www.advsofteng.net/chartdir_cpp_linux_64.tar.gz ]
       File path : [ /mnt/vcpkg-ci/downloads/chartdir_cpp_linux_64-7.0.0.tar.gz.1003174.part ]
   Expected hash : [ e7e71b64b3a756b6df174758c392ab4c9310b4d265e521dccbd009eeefd46e021a74572e7212de5564725df20ddf189e1599e88a116b426f1256f7d34b0131aa ]
     Actual hash : [ ea2e05f28dd9647fed49feaf130d8034065067463965f144b3fae4eae482579b1ecf528dc86d1b3602887d5ca0c3b1569404489b0f4cb2300b798fed940cd467 ]

Updated SHAs and added quotes. These are the changes made by upstream:

```
diff --git a/new_sha/ChartDirector/cppdemo/surfacetexture/surfacetexture.cpp b/old_sha/ChartDirector/cppdemo/surfacetexture/surfacetexture.cpp
index 79f15be..302eb78 100644
--- a/new_sha/ChartDirector/cppdemo/surfacetexture/surfacetexture.cpp
+++ b/old_sha/ChartDirector/cppdemo/surfacetexture/surfacetexture.cpp
@@ -108,7 +108,9 @@ void createChart(int chartIndex, const char *filename)
     const int dataZ_size = dataX_size * dataY_size;
     double dataZ[dataZ_size];
     for(int yIndex = 0; yIndex < dataY_size; ++yIndex) {
+        double y = dataY[yIndex];
         for(int xIndex = 0; xIndex < dataX_size; ++xIndex) {
+            double x = dataX[xIndex];
             dataZ[yIndex * dataX_size + xIndex] = dataX[xIndex] * dataY[yIndex];
         }
     }
@@ -176,7 +178,7 @@ void createChart(int chartIndex, const char *filename)
         // Use a DrawArea to load the image
         DrawArea* d = new DrawArea();
         d->load("maptexture.png");
-        d->resize(c->getPlotRegionWidth(), c->getPlotRegionDepth());
+        d->resize(240, 210);

         // Set the DrawArea as a resource
         c->setResource("texture", d);
diff --git a/new_sha/ChartDirector/lib/libchartdir.so.7.0.0 b/old_sha/ChartDirector/lib/libchartdir.so.7.0.0
index b1ea97f..bfb1d4b 100644
Binary files a/new_sha/ChartDirector/lib/libchartdir.so.7.0.0 and b/old_sha/ChartDirector/lib/libchartdir.so.7.0.0 differ
diff --git a/new_sha/ChartDirector/qtdemo/helloworld/qchartviewer.cpp b/old_sha/ChartDirector/qtdemo/helloworld/qchartviewer.cpp
index 5736d60..423120f 100644
--- a/new_sha/ChartDirector/qtdemo/helloworld/qchartviewer.cpp
+++ b/old_sha/ChartDirector/qtdemo/helloworld/qchartviewer.cpp
@@ -107,9 +107,9 @@ private:
     QCursor *hZoomOutCursor;
     QCursor *hNoZoomCursor;

-    QCursor &getZoomCursor(QCursor **cache, double scale, int flags)
+    QCursor &getZoomCursor(QCursor *cache, double scale, int flags)
     {
-        if (0 == *cache)
+        if (0 == cache)
         {
             DrawArea d;
             d.setSize(32, 32, Chart::Transparent);
@@ -127,9 +127,9 @@ private:
             MemBlock m = d.outPNG();
             QImage img = QImage::fromData((const uchar*)m.data, m.len);
             img.setDevicePixelRatio(scale);
-            *cache = new QCursor(QPixmap::fromImage(img), 15, 15);
+            cache = new QCursor(QPixmap::fromImage(img), 15, 15);
         }
-        return **cache;
+        return *cache;
     }

 public:
@@ -145,15 +145,15 @@ public:
     }
     QCursor &getZoomInCursor(double scale)
     {
-        return getZoomCursor(&hZoomInCursor, scale, 3);
+        return getZoomCursor(hZoomInCursor, scale, 3);
     }
     QCursor &getZoomOutCursor(double scale)
     {
-        return getZoomCursor(&hZoomOutCursor, scale, 1);
+        return getZoomCursor(hZoomOutCursor, scale, 1);
     }
     QCursor &getNoZoomCursor(double scale)
     {
-        return getZoomCursor(&hNoZoomCursor, scale, 0);
+        return getZoomCursor(hNoZoomCursor, scale, 0);
     }
 } cursorManager;

diff --git a/new_sha/ChartDirector/qtdemo/qtdemo/democharts.cpp b/old_sha/ChartDirector/qtdemo/qtdemo/democharts.cpp
index a3b7962..d706853 100644
--- a/new_sha/ChartDirector/qtdemo/qtdemo/democharts.cpp
+++ b/old_sha/ChartDirector/qtdemo/qtdemo/democharts.cpp
@@ -10954,7 +10954,9 @@ void surfacetexture(QChartViewer *viewer, int chartIndex)
     const int dataZ_size = dataX_size * dataY_size;
     double dataZ[dataZ_size];
     for(int yIndex = 0; yIndex < dataY_size; ++yIndex) {
+        double y = dataY[yIndex];
         for(int xIndex = 0; xIndex < dataX_size; ++xIndex) {
+            double x = dataX[xIndex];
             dataZ[yIndex * dataX_size + xIndex] = dataX[xIndex] * dataY[yIndex];
         }
     }
@@ -11022,7 +11024,7 @@ void surfacetexture(QChartViewer *viewer, int chartIndex)
         // Use a DrawArea to load the image
         DrawArea* d = new DrawArea();
         d->load("@/images/maptexture.png");
-        d->resize(c->getPlotRegionWidth(), c->getPlotRegionDepth());
+        d->resize(240, 210);

         // Set the DrawArea as a resource
         c->setResource("texture", d);
@@ -12304,6 +12306,11 @@ void treemapcolors(QChartViewer *viewer, int /* chartIndex */)

 void treemaplayout(QChartViewer *viewer, int chartIndex)
 {
+    // Labels for the tree map
+    const char* energy_types[] = {"Coal", "Oil", "Gas", "Nuclear", "Hydro", "Solar", "Wind",
+        "Biomass", "Geothermal", "Wave"};
+    const int energy_types_size = (int)(sizeof(energy_types)/sizeof(*energy_types));
+
     // Random data for the tree map
     RanSeries* r = new RanSeries(3);
     DoubleArray data = r->getSeries(20, 20, 400);
@@ -14163,10 +14170,7 @@ void circularbarmeter2(QChartViewer *viewer, int chartIndex)
     m->setCap(0, Chart::Transparent);

     // In this example, the circular bar has 20 segments
-    int segmentCount = 20;
-
-    // The angular step
-    double angleStep = 360.0 / segmentCount;
+    int angleStep = 360 / 20;

     // The gap between segments is 4.5 degrees
     double angleGap = 4.5;
@@ -14205,39 +14209,28 @@ void circularbarmeter2(QChartViewer *viewer, int chartIndex)
             stepColorScale_size));
     }

-    //
-    // Now we draw the segments of the bar meter
-    //
-
-    // The segment that contains the value
-    int currentSegment = (int)(angle / angleStep);
-
-    // Segments after the current segment is colored with the blank color
-    for(int i = currentSegment + 1; i < segmentCount; ++i) {
-        m->addRingSector(radius, radius - 20, i * angleStep, (i + 1) * angleStep - angleGap,
-            blankColor);
+    // Draw the blank part of the circular bar
+    if (angle < 360) {
+        // Iterate the segments in the blank part of the circular bar
+        for(int startAngle = (int)(angle / angleStep) * angleStep; startAngle < 360; startAngle +=
+            angleStep) {
+            // The first segment may be partially filled
+            double partialAngle = (startAngle >= angle ? 0 : (angle - startAngle) * (1 - angleGap /
+                angleStep));
+            m->addRingSector(radius, radius - 20, startAngle + partialAngle, startAngle + angleStep
+                 - angleGap, blankColor);
         }
-
-    // Segments before the current segment is colored with the fill color
-    for(int i = 0; i < currentSegment; ++i) {
-        m->addRingSector(radius, radius - 20, i * angleStep, (i + 1) * angleStep - angleGap,
-            fillColor);
     }

-    // Segment that contains the angle will be partially filled and partially blank. We need to
-    // adjust the angle to compensated for the angle gap.
-    double adjustedAngle = currentSegment * angleStep + (angle - currentSegment * angleStep) * (1 -
-        angleGap / angleStep);
-
-    // The blank part of the segment
-    if ((currentSegment + 1) * angleStep > angle) {
-        m->addRingSector(radius, radius - 20, adjustedAngle, (currentSegment + 1) * angleStep -
-            angleGap, blankColor);
+    // Draw the fill part of the circular bar
+    if (angle > 0) {
+        // Iterate the segments in the fill part of the circular bar
+        for(int startAngle = 0; startAngle < angle; startAngle += angleStep) {
+            // The last segment may be partially filled
+            double angleSpan = (angleStep - angleGap) * (angle >= startAngle + angleStep ? 1 : (
+                angle - startAngle) / angleStep);
+            m->addRingSector(radius, radius - 20, startAngle, startAngle + angleSpan, fillColor);
         }
-
-    // The filled part of the segment.
-    if (angle > currentSegment * angleStep) {
-        m->addRingSector(radius, radius - 20, currentSegment * angleStep, adjustedAngle, fillColor);
     }

     // Add a label at the center to display the value
diff --git a/new_sha/ChartDirector/qtdemo/qtdemo/financedemo.cpp b/old_sha/ChartDirector/qtdemo/qtdemo/financedemo.cpp
index 7b8c1f5..b029776 100644
--- a/new_sha/ChartDirector/qtdemo/qtdemo/financedemo.cpp
+++ b/old_sha/ChartDirector/qtdemo/qtdemo/financedemo.cpp
@@ -315,13 +315,6 @@ void FinanceDemo::onLineEditChanged()
     int new_avgPeriod2 = m_MovAvg2->text().toInt();

     QString tickerKey = m_TickerSymbol->text();
-    if (tickerKey.isEmpty())
-    {
-        // Default tickerKey
-        tickerKey = "ASE";
-        m_TickerSymbol->setText(tickerKey);
-    }
-
     QString compareKey = m_CompareWith->text();

     bool needReloadData = (m_tickerKey != tickerKey) || (m_compareKey != compareKey);
@@ -367,16 +360,12 @@ void FinanceDemo::loadData(const QString& ticker, const QString& compare)
     if (m_compareKey != compare)
     {
         m_compareKey = compare;
-        if (m_compareKey.isEmpty())
-            m_dailyPrice.compareData.clear();
-        else
-        {
+
         // Simulator to generate realistic random OHLC values
         FinanceSimulator db2(compare.toUtf8().data(), Chart::chartTime(2010, 1, 1),
             Chart::chartTime(2020, 12, 31), 86400);
         m_dailyPrice.compareData = arrayToVector(db2.getCloseData());
     }
-    }

     // In this example, we will compute the weekly and monthly prices on demand. We just
     // need to clear the old data here.
diff --git a/new_sha/ChartDirector/qtdemo/qtdemo/qchartviewer.cpp b/old_sha/ChartDirector/qtdemo/qtdemo/qchartviewer.cpp
index 5736d60..423120f 100644
--- a/new_sha/ChartDirector/qtdemo/qtdemo/qchartviewer.cpp
+++ b/old_sha/ChartDirector/qtdemo/qtdemo/qchartviewer.cpp
@@ -107,9 +107,9 @@ private:
     QCursor *hZoomOutCursor;
     QCursor *hNoZoomCursor;

-    QCursor &getZoomCursor(QCursor **cache, double scale, int flags)
+    QCursor &getZoomCursor(QCursor *cache, double scale, int flags)
     {
-        if (0 == *cache)
+        if (0 == cache)
         {
             DrawArea d;
             d.setSize(32, 32, Chart::Transparent);
@@ -127,9 +127,9 @@ private:
             MemBlock m = d.outPNG();
             QImage img = QImage::fromData((const uchar*)m.data, m.len);
             img.setDevicePixelRatio(scale);
-            *cache = new QCursor(QPixmap::fromImage(img), 15, 15);
+            cache = new QCursor(QPixmap::fromImage(img), 15, 15);
         }
-        return **cache;
+        return *cache;
     }

 public:
@@ -145,15 +145,15 @@ public:
     }
     QCursor &getZoomInCursor(double scale)
     {
-        return getZoomCursor(&hZoomInCursor, scale, 3);
+        return getZoomCursor(hZoomInCursor, scale, 3);
     }
     QCursor &getZoomOutCursor(double scale)
     {
-        return getZoomCursor(&hZoomOutCursor, scale, 1);
+        return getZoomCursor(hZoomOutCursor, scale, 1);
     }
     QCursor &getNoZoomCursor(double scale)
     {
-        return getZoomCursor(&hNoZoomCursor, scale, 0);
+        return getZoomCursor(hNoZoomCursor, scale, 0);
     }
 } cursorManager;

```