[wxWidgets] Fix issue with port usage (#16154)
Fixed issue when necessary header file was not installed that leaded to this error:
`\vcpkg\installed\x64-windows-static\include\wx\platform.h(160,10): fatal error C1083: Cannot open include file: 'wx/setup.h': No such file or directory`

Also fixed string replace enumeration to include only *.h files because otherwise for some reason *.cur file was messed up.

Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>