[libosip2, talib] Don't install include/makefile.am.
Detected by https://dev.azure.com/vcpkg/public/_build/results?buildId=95376

```
error: The following files are already installed in D:/installed/x86-windows and are in conflict with talib:x86-windows
Installed by libosip2:x86-windows
include/Makefile.am

Stored binaries in 1 destinations in 446 ms.
Elapsed time to handle talib:x86-windows: 40 s
```

Broken by https://github.com/microsoft/vcpkg/pull/34316 which adds talib