[pcre2] Fix -mshstk needed with -fcf-protection
- Fixes the following error:
  src/sljit/sljitConfigInternal.h:219:2: error:
  #error "-mshstk is needed to compile with -fcf-protection"
- Upstream bug report:
  https://bugs.exim.org/show_bug.cgi?id=2578
- Add patch based on upstream commit:
  https://vcs.pcre.org/pcre2?view=revision&revision=1256
- Fixes #12343