Change curl license from null -> "curl"
Curl has its own SPDX license: https://spdx.org/licenses/curl.html

Using `null` for the license triggers an error when building from cmake:

```
-- Running vcpkg install
Errors occurred while parsing ${EXTERNAL_DIR}/vcpkg/ports/curl/vcpkg.json
    $.license: mismatched type: expected an SPDX license expression
Error: Failed to load port curl from ${EXTERNAL_DIR}/vcpkg/ports
Note: Updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
```

It looks like the license line was added in commit [2c0fb4f8200d6917ef79dab3e0d44126995974a1](https://github.com/microsoft/vcpkg/commit/2c0fb4f8200d6917ef79dab3e0d44126995974a1#diff-a91e0d663e8719fb2cb62552c202144c9be4e9a2548b555644fd3399673cddb0), where previously the value was not specified.