[gtk3, gstreamer] Avoid multiple definition of the symbol `properties`.
Hopefully resolves build error on x64-linux: https://dev.azure.com/vcpkg/public/_build/results?buildId=126505

```console
/usr/bin/ld: /mnt/vcpkg-ci/installed/x64-linux/debug/lib/pkgconfig/../../lib/libgtk-3.a(inspector_size-groups.c.o):/mnt/vcpkg-ci/b/gtk3/x64-linux-dbg/../src/NOME-gtk-3-f64471d55d.clean/gtk/inspector/size-groups.c:47: multiple definition of `properties'; subprojects/gstreamer/plugins/elements/libgstcoreelements.a(gstqueue.c.o):/mnt/vcpkg-ci/b/gstreamer/x64-linux-dbg/../src/1.26.5-9c0ab21028.clean/subprojects/gstreamer/plugins/elements/gstqueue.c:130: first defined here
```

I am not sure how to submit these patches to either gtk3 or gstreamer.

This failure started happening between January 19 and January 21; probably caused by #49571