[vamp-sdk] update to 2.10; switch download URL to GitHub; fix path of installed headers (#19572)
* [vamp-sdk] update to 2.10; switch download URL to GitHub

This works around a bad SSL certificate on
https://code.soundsoftware.ac.uk :

Error: Failed to download from mirror set:
https://code.soundsoftware.ac.uk/attachments/download/2589/vamp-plugin-sdk-2.9.0.zip: % Total    % Received % Xferd  Average Speed   Time    Time Time  Current
                                 Dload  Upload   Total   Spent Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

* [vamp-sdk] fix path of installed headers

These are the paths installed by the vamp-plugin-sdk-devel Fedora
package:

/usr/include/vamp
/usr/include/vamp-hostsdk
/usr/include/vamp-hostsdk/Plugin.h
/usr/include/vamp-hostsdk/PluginBase.h
/usr/include/vamp-hostsdk/PluginBufferingAdapter.h
/usr/include/vamp-hostsdk/PluginChannelAdapter.h
/usr/include/vamp-hostsdk/PluginHostAdapter.h
/usr/include/vamp-hostsdk/PluginInputDomainAdapter.h
/usr/include/vamp-hostsdk/PluginLoader.h
/usr/include/vamp-hostsdk/PluginSummarisingAdapter.h
/usr/include/vamp-hostsdk/PluginWrapper.h
/usr/include/vamp-hostsdk/RealTime.h
/usr/include/vamp-hostsdk/host-c.h
/usr/include/vamp-hostsdk/hostguard.h
/usr/include/vamp-hostsdk/vamp-hostsdk.h
/usr/include/vamp-sdk
/usr/include/vamp-sdk/FFT.h
/usr/include/vamp-sdk/Plugin.h
/usr/include/vamp-sdk/PluginAdapter.h
/usr/include/vamp-sdk/PluginBase.h
/usr/include/vamp-sdk/RealTime.h
/usr/include/vamp-sdk/plugguard.h
/usr/include/vamp-sdk/vamp-sdk.h
/usr/include/vamp/vamp.h