[eathread] Remove vcpkg_fail_port_install.
There was no supports expression, and there was ci.baseline.txt impact. The remaining ci.baseline.txt line item was x86-windows, so I tried building that. It results in:

```
C:\Dev\vcpkg2\buildtrees\eathread\src\f21f15bafd-3f7f4715f1.clean\include\eathread/internal/eathread_atomic_standalone_msvc.h(201): error C3861: '_InterlockedExchange64_INLINE': identifier not found
C:\Dev\vcpkg2\buildtrees\eathread\src\f21f15bafd-3f7f4715f1.clean\include\eathread/internal/eathread_atomic_standalone_msvc.h(202): error C3861: '_InterlockedExchangeAdd64_INLINE': identifier not found
C:\Dev\vcpkg2\buildtrees\eathread\src\f21f15bafd-3f7f4715f1.clean\include\eathread/internal/eathread_atomic_standalone_msvc.h(203): error C3861: '_InterlockedExchangeAdd64_INLINE': identifier not found
C:\Dev\vcpkg2\buildtrees\eathread\src\f21f15bafd-3f7f4715f1.clean\include\eathread/internal/eathread_atomic_standalone_msvc.h(204): error C3861: '_InterlockedExchangeAdd64_INLINE': identifier not found
C:\Dev\vcpkg2\buildtrees\eathread\src\f21f15bafd-3f7f4715f1.clean\include\eathread/internal/eathread_atomic_standalone_msvc.h(205): error C3861: '_InterlockedExchangeAdd64_INLINE': identifier not found
C:\Dev\vcpkg2\buildtrees\eathread\src\f21f15bafd-3f7f4715f1.clean\include\eathread/internal/eathread_atomic_standalone_msvc.h(206): error C3861: '_InterlockedOr64_INLINE': identifier not found
C:\Dev\vcpkg2\buildtrees\eathread\src\f21f15bafd-3f7f4715f1.clean\include\eathread/internal/eathread_atomic_standalone_msvc.h(207): error C3861: '_InterlockedAnd64_INLINE': identifier not found
C:\Dev\vcpkg2\buildtrees\eathread\src\f21f15bafd-3f7f4715f1.clean\include\eathread/internal/eathread_atomic_standalone_msvc.h(208): error C3861: '_InterlockedXor64_INLINE': identifier not found
C:\Dev\vcpkg2\buildtrees\eathread\src\f21f15bafd-3f7f4715f1.clean\include\eathread/internal/eathread_atomic_standalone_msvc.h(209): error C3861: '_InterlockedExchange64_INLINE': identifier not found
C:\Dev\vcpkg2\buildtrees\eathread\src\f21f15bafd-3f7f4715f1.clean\include\eathread/internal/eathread_atomic_standalone_msvc.h(216): error C3861: '_InterlockedExchange64_INLINE': identifier not found
C:\Dev\vcpkg2\buildtrees\eathread\src\f21f15bafd-3f7f4715f1.clean\include\eathread/internal/eathread_atomic_standalone_msvc.h(217): error C3861: '_InterlockedExchangeAdd64_INLINE': identifier not found
C:\Dev\vcpkg2\buildtrees\eathread\src\f21f15bafd-3f7f4715f1.clean\include\eathread/internal/eathread_atomic_standalone_msvc.h(218): error C3861: '_InterlockedExchangeAdd64_INLINE': identifier not found
C:\Dev\vcpkg2\buildtrees\eathread\src\f21f15bafd-3f7f4715f1.clean\include\eathread/internal/eathread_atomic_standalone_msvc.h(219): error C3861: '_InterlockedExchangeAdd64_INLINE': identifier not found
C:\Dev\vcpkg2\buildtrees\eathread\src\f21f15bafd-3f7f4715f1.clean\include\eathread/internal/eathread_atomic_standalone_msvc.h(220): error C3861: '_InterlockedExchangeAdd64_INLINE': identifier not found
C:\Dev\vcpkg2\buildtrees\eathread\src\f21f15bafd-3f7f4715f1.clean\include\eathread/internal/eathread_atomic_standalone_msvc.h(221): error C3861: '_InterlockedOr64_INLINE': identifier not found
C:\Dev\vcpkg2\buildtrees\eathread\src\f21f15bafd-3f7f4715f1.clean\include\eathread/internal/eathread_atomic_standalone_msvc.h(222): error C3861: '_InterlockedAnd64_INLINE': identifier not found
C:\Dev\vcpkg2\buildtrees\eathread\src\f21f15bafd-3f7f4715f1.clean\include\eathread/internal/eathread_atomic_standalone_msvc.h(223): error C3861: '_InterlockedXor64_INLINE': identifier not found
C:\Dev\vcpkg2\buildtrees\eathread\src\f21f15bafd-3f7f4715f1.clean\include\eathread/internal/eathread_atomic_standalone_msvc.h(224): error C3861: '_InterlockedExchange64_INLINE': identifier not found
```

which is a build failure in the port, not a CI artifact, so I added that to "supports" as well.

In support of https://github.com/microsoft/vcpkg/pull/21502