[cpprestsdk] Remove _Openprot.
Submitted upstream as https://github.com/microsoft/cpprestsdk/pull/1844

Fixes

```console
REGRESSION: azure-storage-cpp:x64-windows failed with BUILD_FAILED. If expected, add azure-storage-cpp:x64-windows=fail to scripts\ci.baseline.txt.
[...]
FAILED: [code=2] src/CMakeFiles/azurestorage.dir/cloud_append_blob.cpp.obj
C:\PROGRA~2\MICROS~2\18\BUILDT~1\VC\Tools\MSVC\1451~1.362\bin\Hostx64\x64\cl.exe   /TP -DCPPREST_EXCLUDE_WEBSOCKETS=1 -DUNICODE -DWASTORAGE_DLL -D_UNICODE -D_USRDLL -D_WIN32 -Dazurestorage_EXPORTS -ID:\b\azure-storage-cpp\src\v7.5.0-cbdee43b42.clean\Microsoft.WindowsAzure.Storage\includes -external:ID:\vcpkg\installed\x64-windows\include -external:W0 /nologo /DWIN32 /D_WINDOWS /utf-8 /GR /EHsc /MP  /MDd /Z7 /Ob0 /Od /RTC1  /bigobj /MP /Yustdafx.h /showIncludes /Fosrc\CMakeFiles\azurestorage.dir\cloud_append_blob.cpp.obj /Fdsrc\CMakeFiles\azurestorage.dir\ /FS -c D:\b\azure-storage-cpp\src\v7.5.0-cbdee43b42.clean\Microsoft.WindowsAzure.Storage\src\cloud_append_blob.cpp
D:\vcpkg\installed\x64-windows\include\cpprest/filestream.h(1015): error C2039: '_Openprot': is not a member of 'std::ios_base'
C:\Program Files (x86)\Microsoft Visual Studio\18\BuildTools\VC\Tools\MSVC\14.51.36231\include\xiosbase(76): note: see declaration of 'std::ios_base'
D:\vcpkg\installed\x64-windows\include\cpprest/filestream.h(1015): note: the template instantiation context (the oldest one first) is
D:\b\azure-storage-cpp\src\v7.5.0-cbdee43b42.clean\Microsoft.WindowsAzure.Storage\src\cloud_append_blob.cpp(206): note: see instantiation of default argument expression required for 'Concurrency::task<Concurrency::streams::istream> Concurrency::streams::file_stream<uint8_t>::open_istream(const utility::string_t &,std::ios_base::openmode,int)'
D:\vcpkg\installed\x64-windows\include\cpprest/filestream.h(1015): error C2065: '_Openprot': undeclared identifier
```

on Visual Studio 2026 19.6.0 / MSVC 19.51.

azure-storage-cpp meets our normal criteria for being deindexed but I have an internal Microsoft customer asking for this to be fixed. No promises that we don't fix it and then immediately remove it.