[clickhouse-cpp] update to 1.5.0 (#18330)
* [clickhouse-cpp] update to 1.2.2

* update version

* [clickhouse-cpp] update to 1.5.0

* update version

* fix error c4996

* update version

* merge baseline.json

* update baseline.json

* add Add patch description

* update version

* Add patch comment

* update version