[nu-book-zxing-cpp] New port  (#22657)
* Upgraded zxing-cpp port to use the source code from https://github.com/nu-book/zxing-cpp

* Removed outdated patch files

* Added patch files to remove unnecessary install .pdb . Not needed cause lib is created using /Z7. Debug symbols are embedded in the .lib

* Updated helper functions as per maintainers guidelines

* Braces error

* Added vcpkg-cmake-config and vcpkg-cmake as host dependencies

* CHanged TARGET to PACKAGE_NAME

* Ran format manifest

* Ran x-add-version

* Update vcpkg.json

* Add git as host dependency cause of ExternalProject.cmake:2650 (message):
  error: could not find git for clone of fmtlib-populate.
Fix version as per feedback

* Removed git.. does not exist

* Set build blackbox test and examples to default to OFF

* Ran x-add-versions --all

* Change source_path for uwp

* Remove quotes

* update SHA

* Removed unused options when building for uwp

* add version

* Force type release for uwp

* ran add version

* Copy zxing.pc only if not UWP

* version fix

* Fix licence location if building uwp

* ran x-add-version

* remove NOT silly mistake

* ran add version

* Removed unnecessary change of source path to build winrt sdk.

* Update version

* Added flag and MS build option to vcpkg cmake configure

* Add -wd4996 flag to ignore deprecated function warning in v142 VCPKG Build tools for WindowStore

* add version

* Use VCPKG_TARGET_IS_UWP instead of STREQUAL "WindwosStore"

Co-authored-by: JonLiu1993 <63675417+JonLiu1993@users.noreply.github.com>

* Added quotes as per review feedback

* Fixed versioning as per feedback

* Add licence to vcpkg.json

* Update version

* Removed unnecessary copy of template .pc.in file. CMake takes care of generating the correct .pc file and puts it in the right place.

* Add versions

* Using extra options to avoid two vcpkg configure

* add version

* Revert back to the original port

* Add new package nu-book-zxing

* Updated baseline with new port

* Removed non-existence version

* Add nu-book-zxing-cpp version

* Put correct package name in vcpkg.json

Co-authored-by: Jack·Boos·Yu <47264268+JackBoosY@users.noreply.github.com>

* Update version and add skip to baseline

* [nu-book-zxing-cpp][zxing-cpp] Remove abandoned port, promote nu-book fork

* Add "supports": "!uwp"

Co-authored-by: Jack·Boos·Yu <47264268+JackBoosY@users.noreply.github.com>

* Update version database

Co-authored-by: JonLiu1993 <63675417+JonLiu1993@users.noreply.github.com>
Co-authored-by: Jack·Boos·Yu <47264268+JackBoosY@users.noreply.github.com>
Co-authored-by: Robert Schumacher <roschuma@microsoft.com>