[hyperscan] Disable unit tests.
Also avoids old vendored copy of Google Test that fails on MSVC 19.51+ due to the removal of std::tr1::tuple:

```console
\unit\gtest/gtest.h(9688): error C2039: 'tr1': is not a member of 'std'
C:\Program Files (x86)\Microsoft Visual Studio\18\BuildTools\VC\Tools\MSVC\14.51.36231\include\set(22): note: see declaration of 'std'
\unit\gtest/gtest.h(9688): error C3083: 'tr1': the symbol to the left of a '::' must be a type
\unit\gtest/gtest.h(9693): error C3083: 'tr1': the symbol to the left of a '::' must be a type
\unit\gtest/gtest.h(9698): error C3083: 'tr1': the symbol to the left of a '::' must be a type
\unit\gtest/gtest.h(9703): error C3083: 'tr1': the symbol to the left of a '::' must be a type
```

Also minimized remove-werror patch