[qt5-webengine] Work around mixed protobuf issue (#37044)
On MS Windows qt5-webengine fails to build in a context where protobuf
from vcpkg is also used because it includes the vcpkg supplied version
of protobuf headers when building the Qt part of the code in
qt5-webengine, against the internal copy of Chromium which has used its
older copy of protobuf to generate the headers. The build failure seen
is this:

    FAILED: obj/QtWebEngineCore/browser_message_filter_qt.obj
    ...
    ...

C:\vcpkgroot\qt5-webengine\x64-windows-dbg\src\core\debug\gen\net/third_party/quiche/src/quic/core/proto/cached_network_parameters.pb.h(17):
fatal error C1189: #error: This file was generated by an older version
of protoc which is

To work around this issue we ensure that the path to the chromium
provided version of protobuf is included before the path to the vcpkg
provided includes residing in:

    C:/vcpkgroot/qt5-webengine/x64-windows-dbg/include

Fixes #12150
Fixes #27932
Fixes #34452

- [x] Changes comply with the [maintainer
guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this
new version.
- [x] Any fixed [CI
baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)
entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's
directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version
--all` and committing the result.
- [x] Only one version is added to each modified port's versions file.