[mathgl] URL Encode
Workaround on Ubuntu 22.04:

error: https://sourceforge.net/projects/mathgl/files/mathgl/mathgl 8.0/mathgl-8.0.1.tar.gz/download: curl failed to download with exit code 3
curl: (3) URL using bad/illegal format or missing URL