[cppmicroservices] Devendor spdlog.
Fixes:

```
\third_party\spdlog\include\spdlog\fmt\bundled\format.h(490): error C2653: 'stdext': is not a class or namespace name
\third_party\spdlog\include\spdlog\fmt\bundled\format.h(490): error C2061: syntax error: identifier 'checked_array_iterator'
\third_party\spdlog\include\spdlog\fmt\bundled\format.h(492): error C3613: missing return type after '->' ('int' assumed)
\third_party\spdlog\include\spdlog\fmt\bundled\format.h(492): error C3646: 'checked_ptr': unknown override specifier
\third_party\spdlog\include\spdlog\fmt\bundled\format.h(492): error C2988: unrecognizable template declaration/definition
\third_party\spdlog\include\spdlog\fmt\bundled\format.h(492): error C2059: syntax error: '<'
\third_party\spdlog\include\spdlog\fmt\bundled\format.h(492): error C2143: syntax error: missing ';' before '{'
\third_party\spdlog\include\spdlog\fmt\bundled\format.h(492): error C2447: '{': missing function header (old-style formal list?)
\third_party\spdlog\include\spdlog\fmt\bundled\format.h(510): error C3613: missing return type after '->' ('int' assumed)
\third_party\spdlog\include\spdlog\fmt\bundled\format.h(504): warning C4346: 'value': dependent name is not a type
\third_party\spdlog\include\spdlog\fmt\bundled\format.h(504): note: prefix the qualified-id with 'typename' to indicate a type
\third_party\spdlog\include\spdlog\fmt\bundled\format.h(510): error C3646: 'checked_ptr': unknown override specifier
\third_party\spdlog\include\spdlog\fmt\bundled\format.h(510): error C2988: unrecognizable template declaration/definition
\third_party\spdlog\include\spdlog\fmt\bundled\format.h(510): error C2059: syntax error: '<'
\third_party\spdlog\include\spdlog\fmt\bundled\format.h(510): error C2143: syntax error: missing ';' before '{'
\third_party\spdlog\include\spdlog\fmt\bundled\format.h(510): error C2447: '{': missing function header (old-style formal list?)
\third_party\spdlog\include\spdlog\fmt\bundled\format.h(545): warning C4346: 'value': dependent name is not a type
\third_party\spdlog\include\spdlog\fmt\bundled\format.h(545): note: prefix the qualified-id with 'typename' to indicate a type
\third_party\spdlog\include\spdlog\fmt\bundled\format.h(547): error C2061: syntax error: identifier 'checked_ptr'
\third_party\spdlog\include\spdlog\fmt\bundled\format.h(2807): error C3861: 'make_checked': identifier not found
```