[ixwebsocket] update to 6.1.0 to fix Windows problem (#7839)
* [ixwebsocket] update to 5.0.6 to fix Windows problem

Some test started to fail on Windows in the 5.0 branch.
```
ERROR: Unable to connect to echo.websocket.org on port 80, error: Connect error: No error
ERROR: Unable to connect to echo.websocket.org on port 80, error: Connect error: No error
ERROR: Unable to connect to echo.websocket.org on port 80, error: Connect error: No error
ERROR: Unable to connect to echo.websocket.org on port 80, error: Connect error: No error
ERROR: Unable to connect to echo.websocket.org on port 80, error: Connect error: No error
ERROR: Unable to connect to echo.websocket.org on port 80, error: Connect error: No error
ERROR: Unable to connect to echo.websocket.org on port 80, error: Connect error: No error
```
We figured it out and fixed it. This issue has more details. https://github.com/machinezone/IXWebSocket/issues/103

* ixwebsocket: update to 6.1.0