Revert "[vtk] Fix features and cross builds (#46843)"
This reverts commit eb2266e1feafbc371eb317b4798e6e5905f489b5 / https://github.com/microsoft/vcpkg/pull/46843

Resolves:

Installing 2155/2243 vtk-compile-tools:x64-windows@9.3.0-pv5.12.1...
Building vtk-compile-tools:x64-windows@9.3.0-pv5.12.1...
-- Using cached Kitware-VTK-09a76bc55b37caad94d0d8ebe865caaed1b438af.tar.gz
-- Extracting source D:/downloads/Kitware-VTK-09a76bc55b37caad94d0d8ebe865caaed1b438af.tar.gz
-- Using source at D:/b/vtk-compile-tools/src/aed1b438af-c216954790.clean
-- Found external ninja('1.12.1').
-- Configuring x64-windows
-- Building x64-windows-rel
-- Installing: D:/p/vtk-compile-tools_x64-windows/share/vtk-compile-tools/copyright
-- Performing post-build validation
error: The following files are already installed in D:/installed/x64-windows and are in conflict with vtk-compile-tools:x64-windows
Installed by vtk:x64-windows:
  bin/vtkWrappingTools-9.3.dll
  bin/vtkWrappingTools-9.3.pdb
  lib/vtkWrappingTools-9.3.lib
Starting submission of vtk-compile-tools:x64-windows@9.3.0-pv5.12.1 to 1 binary cache(s) in the background
Elapsed time to handle vtk-compile-tools:x64-windows: 21 s
vtk-compile-tools:x64-windows package ABI: 414bb0b5267a2a9a15788c642e98f19e06ba5f657d1b0efae3aa70bdb2d55cc9