[urho3d] Disable warning broken on current macOS
This port has so much vendored stuff and is no longer maintained so I think it should probably be deindexed but this is enough for now.

```
/Users/vagrant/Data/buildtrees/urho3d/src/3eb4f765c8-520911ca5c.clean/Source/ThirdParty/SDL/src/file/cocoa/SDL_rwopsbundlesupport.m
/Users/vagrant/Data/buildtrees/urho3d/src/3eb4f765c8-520911ca5c.clean/Source/ThirdParty/SDL/src/file/cocoa/SDL_rwopsbundlesupport.m:45:20: error: mixing declarations and code is incompatible with standards before C99 [-Werror,-Wdeclaration-after-statement]
    NSFileManager* file_manager = [NSFileManager defaultManager];
                   ^
1 error generated.
```