[folly] Remove vcpkg_fail_port_install.
vcpkg.json was missing the uwp skip but otherwise agreed. There is no ci.baseline.txt impact because:

     Error: libevent[core] is only supported on '!uwp'

In support of https://github.com/microsoft/vcpkg/pull/21502