[pcl[cuda]] Fix build failure (#37041)
Fixes #33527

Add VTK as a dependency to CUDA feature. and use upstream patch to fix
error:
````
LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library
screenshot_manager.cpp.obj : error LNK2019: unresolved external symbol "void __cdecl pcl::io::saveRgbPNGFile(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned char const *,int,int)" (?saveRgbPNGFile@io@pcl@@YAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEBEHH@Z) referenced in function "public: void __cdecl pcl::kinfuLS::ScreenshotManager::saveImage(class Eigen::Transform<float,3,2,0> const &,struct pcl::gpu::PtrStepSz<struct pcl::gpu::kinfuLS::PixelRGB const >)" (?saveImage@ScreenshotManager@kinfuLS@pcl@@QEAAXAEBV?$Transform@M$02$01$0A@@Eigen@@U?$PtrStepSz@$$CBUPixelRGB@kinfuLS@gpu@pcl@@@gpu@3@@Z)

bin\pcl_gpu_kinfu_large_scaled.dll : fatal error LNK1120: 1 unresolved externals
````
The upstream PR: https://github.com/PointCloudLibrary/pcl/pull/5947

All features are tested successfully in the following triplet:
x86-windows
x64-windows
x64-windows-static

- [x] Changes comply with the [maintainer
guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ ] ~~SHA512s are updated for each updated download.~~
- [ ] ~~The "supports" clause reflects platforms that may be fixed by
this new version.~~
- [ ] ~~Any fixed [CI
baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)
entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the
port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version
--all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

---------

Co-authored-by: Jon <v-zhli17@microsoft.com>